#ifndef AI_ALBUM_UI_ROUTE_H
#define AI_ALBUM_UI_ROUTE_H

typedef enum {
    AI_ALBUM_UI_ROUTE_HOME = 0,
    AI_ALBUM_UI_ROUTE_ALBUM,
    AI_ALBUM_UI_ROUTE_GALLERY,
    AI_ALBUM_UI_ROUTE_IMAGE_AI,
    AI_ALBUM_UI_ROUTE_TRANSLATE,
    AI_ALBUM_UI_ROUTE_AI_CHAT,
    AI_ALBUM_UI_ROUTE_PRACTICE,
    AI_ALBUM_UI_ROUTE_SETTINGS,
    AI_ALBUM_UI_ROUTE_SETTINGS_WIFI,
    AI_ALBUM_UI_ROUTE_SETTINGS_LOCATION,
    AI_ALBUM_UI_ROUTE_SETTINGS_LOCATION_SEARCH,
    AI_ALBUM_UI_ROUTE_SETTINGS_WIFI_PASSWORD,
    AI_ALBUM_UI_ROUTE_COUNT,
    AI_ALBUM_UI_ROUTE_NONE = AI_ALBUM_UI_ROUTE_COUNT,
} ai_album_ui_route_t;

#endif
